# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bitcoin Price' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bitcoin Price
  
   # Charts (Beautiful charts for iOS/tvOS/OSX)
   # https://github.com/danielgindi/Charts
   pod 'Charts'
  
  # Gradient Animation for views
  # https://github.com/cruisediary/Pastel
   pod "Pastel", :inhibit_warnings => true
   
   
  target 'Bitcoin PriceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Bitcoin PriceUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
