# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bitcoin Price' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bitcoin Price

  # Alamofire (HTTP networking)
  # https://github.com/Alamofire/Alamofire
  pod 'Alamofire', '~> 4.6.0'
  
  # Charts (Beautiful charts for iOS/tvOS/OSX)
  # https://github.com/danielgindi/Charts
  pod 'Charts', '~> 3.0.5'
  
  target 'Bitcoin PriceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Bitcoin PriceUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
