platform :ios, '9.0'

target 'Bitcoin Price' do
    use_frameworks!
    
    # Alamofire (HTTP networking)
    # https://github.com/Alamofire/Alamofire
    pod 'Alamofire', '~> 4.6.0'
    
    # Charts (Beautiful charts for iOS/tvOS/OSX)
    # https://github.com/danielgindi/Charts
    pod 'Charts', '~> 3.0.5'
  
    
    # NotificationBanner (highly customizable in app notification banners)
    # https://github.com/Daltron/NotificationBanner
    pod 'NotificationBannerSwift', '~> 1.6.1'
    
    pod "Pastel", :inhibit_warnings => true
     
    target 'Bitcoin PriceTests' do
        inherit! :search_paths
    end
    
    target 'Bitcoin PriceUITests' do
        inherit! :search_paths
    end


end


